MOPITT multiple granule handling
Added code to handle multiple MOPITT files. Was not able to verify it works because of infinite loop problem with CERES code in main.c.

diff --git a/bin/jobSubmit b/bin/jobSubmit
--- a/bin/jobSubmit
+++ b/bin/jobSubmit
@@ -15,6 +15,11 @@ else
     unset TERRA_DATA_PACK
 fi
 
+while [[ $inFile != 1 && $inFile != 2 ]]; do
+    printf "Use inputFiles.txt already present in your exe directory [1] or generate new one [2]? "
+    read inFile
+done
+
 cd "$PROJDIR"/bin
 
 printf "\e[92m\e[4mLoading modules\e[0m\n"
@@ -28,13 +33,27 @@ if [ "$status" -ne 0 ]; then
     exit 1
 fi
 
-printf "\e[92m\e[4mGenerating input file list\e[0m\n"
-./generateInput.sh "$inputFiles" "$PROJDIR"/exe/inputFiles.txt
-status=$?
-if [ "$status" -ne 0 ]; then
-    printf "\e[91m\e[4mFatal error\e[0m: generateInput.sh returned with an exit status of $status.\nAborting script.\n"
-    exit 1
+input=0
+
+
+
+if [[ $inFile == 2 ]]; then
+    printf "\e[92m\e[4mGenerating input file list\e[0m\n"
+    ./generateInput.sh "$inputFiles" "$PROJDIR"/exe/autoGenInputFiles.txt
+    status=$?
+    if [ "$status" -ne 0 ]; then
+        printf "\e[91m\e[4mFatal error\e[0m: generateInput.sh returned with an exit status of $status.\nAborting script.\n"
+        exit 1
+    fi
+
+    # Modify first line in batchscript.pbs to contain proper variable declaration for the proper inputFiles.txt file
+    var="FILELISTNAME=autoGenInputFiles.txt"
+else
+    var="FILELISTNAME=inputFiles.txt"
 fi
+
+# replace 4th line in batchscript.pbs with var
+sed -n "4s/.*/$var/" "$PROJDIR"/bin/batchscript.pbs
 
 printf "\e[92m\e[4mSubmitting job to scheduler\e[0m\n"
 qsub -v TERRA_DATA_PACK "$PROJDIR"/bin/batchscript.pbs
